[
    uuid(50C2504F-1062-4CC3-B9F1-9329A3BE82F9),
    version(1.0),
    implicit_handle(handle_t hDemoBinding)
]

interface demo
{
    import "oaidl.idl";
    import "demo.h";

    typedef struct RPCSTRING {
        unsigned long size;
        [ ptr, size_is(size), length_is(size) ] wchar_t str[*];
    } RPCSTRING_t;
    typedef RPCSTRING_t* PRPCSTRING;
    typedef RPCSTRING_t** PPRPCSTRING;

    typedef struct Contact {
        int age;
        BSTR name;
        BSTR mobile;
        BSTR address;
    }Contact_t;
    typedef Contact_t* PContact_t;
    typedef Contact_t** PPContact_t;

    int SendString([ in, string ] const wchar_t *msg);
    int GetString([ in, string ] const wchar_t *inStr, [ out, string ] wchar_t outStr[128]);
    int GetVarString([ in, string ] const wchar_t *inStr, [out] PRPCSTRING *outStr);
    int GetVarStringList([ in, string ] const wchar_t *inStr, [out] int *pNum,
                         [ out, size_is(, *pNum) ] PPRPCSTRING *outStrList);
    int GetContact([out] PContact_t contact);
    int GetContactList([out] int* pNum, [out, size_is(, *pNum)] PPContact_t *contact);
    void Shutdown(void);
}
