[
    uuid(ed838ecd-8a1e-4da7-bfda-9f2d12d07893),
    version(1.0),
    implicit_handle(handle_t hDemoBinding)
]
interface demo
{
    import "demo.h";

    int SendString([in, string] const wchar_t* msg);
    int GetString([in, string] const wchar_t* inStr, [out, string] wchar_t outStr[128]);
    void Shutdown(void);
}
